questions =  [
    {"id": 0, "question": "Skipdotting should be banned.", "effects": {"right": 1}},
    {"id": 1, "question": "Sinking should be banned.", "effects": {"right": 1}},
    {"id": 2, "question": "Lining should be banned.", "effects": {"right": 1}},
    {"id": 3, "question": "Framing should be banned.", "effects": {"right": 1}},
    {"id": 4, "question": "Dotting should be banned.", "effects": {"right": 1}},
    {"id": 5, "question": "Botting should be banned on MVP.", "effects": {"right": 1}},
    {"id": 6, "question": "The current art rules are good.", "effects": {"right": 1}},
    {"id": 7, "question": "The current chat rules are good.", "effects": {"right": 1}},
    {"id": 8, "question": "People who dislike rules should just go to PWW instead of complaining on MVP.", "effects": {"right": 1}},
    {"id": 9, "question": "We need more rules.", "effects": {"right": 1}},
    {"id": 10, "question": "JustCallMeSimon/SoManyNames is a good mod.", "effects": {"auth": 1}},
    {"id": 11, "question": "Kyle Bowman is a good mod.", "effects": {"auth": 1}},
    {"id": 12, "question": "AlmosYT is a good mod.", "effects": {"auth": 1}},
    {"id": 13, "question": "Ghello is a good mod.", "effects": {"auth": 1}},
    {"id": 14, "question": "XXV6 is a good mod.", "effects": {"auth": 1}},
    {"id": 15, "question": "Kaiser Kazali/Kazali is a good mod.", "effects": {"auth": 1}},
    {"id": 16, "question": "Owmince has done a good job choosing the mods.", "effects": {"auth": 1}},
    {"id": 17, "question": "Mods don't need limits on their power.", "effects": {"auth": 1}},
    {"id": 18, "question": "Mods should have more power.", "effects": {"auth": 1}},
    {"id": 19, "question": "Parliament should have more power.", "effects": {"auth": 1}},
];
